version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.2.0
    working_directory: ~/repo
    steps:
      - checkout

      - run: sudo npm i -g pnpm@6.3.0
      - run: pnpm i
      - run: pnpm run build -r
      - run: pnpm run lint
      - run: pnpm t
      - run: pnpm run coverage
      - run: pnpm run type-coverage

      - persist_to_workspace:
          root: .
          paths:
            - packages/*/dist/*

  publish:
    docker:
      - image: circleci/node:16.2.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: sudo npm i -g pnpm@5.10.1
      - run: pnpm i --frozen-lockfile
      - run: pnpm -r publish --access public --no-git-checks

workflows:
  version: 2
  package:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          context: iyegoroff
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
